# Generated by cucumber-sinatra. (2014-11-15 15:40:36 +0000)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'app/server.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = Rock-Paper-Scissors

class Rock-Paper-ScissorsWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  Rock-Paper-ScissorsWorld.new
end
